# Generated by Django 4.1.7 on 2023-02-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_cliente_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='entrgado',
            new_name='entregado',
        ),
    ]
